DROP SCHEMA IF EXISTS `subsidy` ;
CREATE SCHEMA `subsidy` ;
USE `subsidy` ;

DROP TABLE IF EXISTS `subsidy`.`payments`;
DROP TABLE IF EXISTS `subsidy`.`recipients`;
DROP TABLE IF EXISTS `subsidy`.`subsidies`;
DROP TABLE IF EXISTS `subsidy`.`government`;

CREATE TABLE `subsidy`.`government` (
  `ETH_ACCOUNT_ADDRESS` VARCHAR(200),
  `CREATION_DATE` TIMESTAMP,
  `STATE_NAME` VARCHAR(20),
  `COUNTRY` VARCHAR(20),
  PRIMARY KEY (`ETH_ACCOUNT_ADDRESS`));

CREATE TABLE `subsidy`.`subsidies` (
  `SUBSIDY_ID` INT(10) AUTO_INCREMENT ,
  `SUBSIDY_NAME` VARCHAR(20) ,
  `CONSUMED` TINYINT(1) ,
  `AMOUNT` DOUBLE ,
  PRIMARY KEY (`SUBSIDY_ID`));
  
CREATE TABLE `subsidy`.`recipients` (
  `AADHAR_NUMBER` VARCHAR(12) NOT NULL,
  `ETH_ACCOUNT_ADDRESS` VARCHAR(200) ,
  PRIMARY KEY (`AADHAR_NUMBER`),
  CONSTRAINT `FK_ETH_ADDRESS`
    FOREIGN KEY (`ETH_ACCOUNT_ADDRESS`)
    REFERENCES `subsidy`.`government` (`ETH_ACCOUNT_ADDRESS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE TABLE `subsidy`.`payments` (
  `SUBSIDY_ID` INT(10) NOT NULL,
  `AADHAR_NUMBER` VARCHAR(12) ,
  `AMOUNT` DOUBLE ,
  `TRANSACTION_ID` VARCHAR(45),
  `CREATED_DATE` TIMESTAMP ,
  PRIMARY KEY (`SUBSIDY_ID`),
  CONSTRAINT `FK_SUBSIDY_ID`
    FOREIGN KEY (`SUBSIDY_ID`)
    REFERENCES `subsidy`.`subsidies` (`SUBSIDY_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_AADHAR_CARD`
    FOREIGN KEY (`AADHAR_NUMBER`)
    REFERENCES `subsidy`.`recipients` (`AADHAR_NUMBER`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

INSERT INTO `subsidy`.`government` (`ETH_ACCOUNT_ADDRESS`, `STATE_NAME`, `COUNTRY`) VALUES ('0xa2c9392936e5019d93d1f7bf9fd3d5f4333c022b', 'Maharashtra', 'India');

INSERT INTO `subsidy`.`subsidies` (`SUBSIDY_NAME`, `CONSUMED`, `AMOUNT`) VALUES ('Education Subsidy', '1', '10000');
INSERT INTO `subsidy`.`subsidies` (`SUBSIDY_NAME`, `CONSUMED`, `AMOUNT`) VALUES ('Farmer Subsidy', '0', '20000');

INSERT INTO `subsidy`.`recipients` (`AADHAR_NUMBER`, `ETH_ACCOUNT_ADDRESS`) VALUES ('456298743256', '0xa2c9392936e5019d93d1f7bf9fd3d5f4333c022b');
INSERT INTO `subsidy`.`recipients` (`AADHAR_NUMBER`, `ETH_ACCOUNT_ADDRESS`) VALUES ('479658213695', '0xa2c9392936e5019d93d1f7bf9fd3d5f4333c022b');

INSERT INTO `subsidy`.`payments` (`SUBSIDY_ID`, `AADHAR_NUMBER`, `AMOUNT`, `TRANSACTION_ID`) VALUES ('1', '456298743256', '10000', '0x01aad8dbac1aea485e33d2');
